services:
  ecommerce-api2:
    build:
      context: . 
      dockerfile: Dockerfile
    ports: 
    - '3000:3000'
    env_file:
      - .env.development.local
    depends_on: 
     - postgres2
    networks:
     - ecommerce-app2


  postgres2:
      image: postgres:17
      container_name: postgres2
      env_file:
      - .env.development.local
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - '5432:5432'
      networks:
        - ecommerce-app2

 

volumes:
  postgres_data:

networks:
  ecommerce-app2:
    driver: bridge

