import { User } from 'src/modules/users/entities/user.entity';
import {
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { OrderDetail } from '../../ordersDetail/entities/order-detail.entity';
import { ApiProperty } from '@nestjs/swagger';

@Entity()
export class Order {
  @ApiProperty({
    description: 'autogenerated uuid'
  })
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ApiProperty({
    description: 'N:1 relation with user'
  })
  @ManyToOne(() => User, (user) => user.orders)
  user_id: User;

  @ApiProperty({
    description: "date of order"
  })
  @Column('date')
  date: Date;

  @ApiProperty({
    description: "order's detail"
  })
  @OneToOne(() => OrderDetail, {cascade: true})
  @JoinColumn()
  order_detail: OrderDetail;
}
